server:
  port: 8088
spring:
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: false
      dialect: org.hibernate.dialect.Oracle12cDialect
    database-platform: org.hibernate.dialect.Oracle12cDialect
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: HR
    password: hr
    driver-class-name: oracle.jdbc.driver.OracleDriver
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
token:
  expired:
    time-in-days: 7
jwt:
  secret: springboot
ptm:
  url: http://172.104.47.232:8080
